---
title: Girish Godage
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image: ''
    author: ''
    layout: posts
    prevurl: ''
    nexturl: ''
- scope:
    path: ''
    type: pages
  values:
    image: ''
    layout: page
baseurl: ''
url: https://girishgodage.in
domainurl: https://girishgodage.in
google_verification: 
google_analytics: UA-130164763-2
google_tag_manager: 
bing_verification: 
github_username: girishgodage
bitbucket_username: 
stackoverflow_id: 
twitter_username: GGodage
skype_username: 
steam_nickname: 
google_plus_id: 
linkedin_username: girishgodage_007
angellist_username: 
medium_id: 
bitcoin_url: 
paypal_url: 
flattr_button: 
show_sharing_icons: false
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false
text:
  pagination:
    newer: Newer
    older: Older
  share_buttons:
    text: Share this post!
    facebook: Share on Facebook
    twitter: Share on Twitter
    googleplus: Share on Google+
    linkedin: Share on LinkedIn
    digg: Share on Digg
    tumblr: Share on Tumblr
    reddit: Share on Reddit
    stumbleupon: Share on StumbleUpon
    hackernews: Share on Hacker News
  post:
    updated: Updated
    minute_read: minute read
    related_posts: Related Posts
  index:
    coming_soon: Coming soon...
  og_locale: en_US
markdown: kramdown
exclude:
- Gemfile
tagline: Passionate Leader, who has a good command in technology & Management
description: I am a passionate Leader, who has a good command in technology & Mangement.
  Also, I am a creative designer and an innovatie techie.
keywords: Girish Godage, Girish Godage007, girish godage, girish, godage, girish godage,
  girish godage github blog, girish godage yt,Software Design,Software Architect,SpringBootMicroservice,PythonTutorial,AngularTutorial
author: Girish Godage
permalink: pretty
comments: true
plugins:
- jekyll-feed
- jekyll-admin
