markdown: kramdown

exclude:
  - Gemfile

title: Girish Godage
tagline: Passionate Leader, who has a good command in technology & Management
description: I am a passionate Leader, who has a good command in technology & Mangement. Also, I am a creative designer and an innovatie techie.
keywords: Girish Godage, Girish Godage007, girish godage, girish, godage, girish godage, girish godage github blog, girish godage yt

author: Girish Godage